### ISSUE TITLE
Add support for for alternative operation syntax

### ISSUE THREAD

**Issue by louiscollarsmith** [RomiC/rsql-builder#114]
Where applicable, an Operation should give the option of using an alternative syntax. Examples of the alternative syntaxes are below. These alternatives were copied from https://github.com/jirutka/rsql-parser .

Equal to : ==
Not equal to : !=
Less than : =lt= or <
Less than or equal to : =le= or <=
Greater than operator : =gt= or >
Greater than or equal to : =ge= or >=
In : =in=
Not in : =out=

The value of these alternative syntax is that they don't require any encodings for use in URLs.

An example implementation with less than:

```
export enum OperatorType {
    DEFAULT = 0;
    ALTERNATIVE = 1;
}

export enum DefaultOperators {
  EQUAL = '==',
  NOT_EQUAL = '!=',
  LESS_THAN = '<',
  LESS_OR_EQUAL = '<=',
  GREATER_THAN = '>',
  GREATER_OR_EQUAL = '>=',
  IN = '=in=',
  OUT = '=out='
}

export enum AlternativeOperators {
  EQUAL = '==',
  NOT_EQUAL = '!=',
  LESS_THAN = '=lt=',
  LESS_OR_EQUAL = '=le=',
  GREATER_THAN = '=gt=,
  GREATER_OR_EQUAL = '=ge=',
  IN = '=in=',
  OUT = '=out='
}

export function le(argument: any, operatorType: OperatorType = OperatorType.DEFAULT): Operation {
      // Operation would take the operatorType and pick the relevant operator, be it default or alternative.
      return new Operation(argument, Operators.LESS_OR_EQUAL, opType);
}
```

This is not exactly how i would implement, but gives an idea of what could be done.

**Comment by louiscollarsmith** [comment]
@RomiC Does this make sense? I'm willing to contribute if you believe its valuable; it would be value for myself and my team!

**Comment by RomiC** [comment]
@louiscollarsmith, sorry, looks like I've missed the notification about your PR 😢 Sure, feel free to contribute to this project. That's absolutely make sense.
