### ISSUE TITLE
Angular10 rsql builder not able to remove %22 in the inlist result[UI}

### ISSUE THREAD

**Issue by lavanyaaks** [RomiC/rsql-builder#126]
Getting %22 for inList as below.

deviceType=in=(%22pos,controller%22)
model = in = (%1,2%)

model = ['1','2']
device = ['pos','controller']
using the below query in the angular ui component.installed rsql query builder packege.

query = and( or( comparison('deviceType', inList(device)), comparison('model', inList(model) ) );

I am new to rsql in angular 10.

could you please help ASAP on this?

**Comment by RomiC** [comment]
@lavanyaaks sorry for long response, I've missed the notification about it. My guess the problem is about wrong usage of `inList`-operator. It accepts the list of arguments, but not an array. Try to replace with the following:
```ts
const query = and(
  or(
    comparison('deviceType', inList(...device)),
    comparison('model', inList(...model))
  )
);
```
